transactions:
  json:
    path: ./src/main/resources/transactions/transactions.json

spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:main
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

---

spring:
  config:
    activate:
      on-profile: integration
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect



